services:
  - type: web
    name: british-auction-backend
    env: docker
    region: ohio
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
